name: dockerhub-deploy
on:
  push:
    branches:
      - main

jobs:
  gradle-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew check installDist

      - uses: actions/cache@v3
        with:
          path: replicator/build/install/replicator
          key: gradle-install:${{ github.sha }}

  docker-build:
    needs: gradle-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: replicator/build/install/replicator
          key: gradle-install:${{ github.sha }}

      - run: docker build . -t ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }} --build-arg MODULE=replicator

      - run: mkdir shared
      - run: docker save ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }} > shared/replicator.tar

      - uses: actions/cache@v3
        with:
          path: shared/replicator.tar
          key: docker-build:${{ github.sha }}

  docker-push:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: shared/replicator.tar
          key: docker-build:${{ github.sha }}

      - run: docker load < shared/replicator.tar
      - run: docker tag ${{ vars.DOCKER_IMAGE_NAME }}:"$GITHUB_SHA" ${{ vars.DOCKER_IMAGE_NAME }}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push
        run: |
          docker push ${{ vars.DOCKER_IMAGE_NAME }}:"$GITHUB_SHA"
          docker push ${{ vars.DOCKER_IMAGE_NAME }}:latest
