name: pr
on:
  push:
    branches:
      - main

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew check
